"""add auth tenancy tables and project_id/economics columns

Revision ID: 0e47b2d10b47
Revises: f45d3034c58d
Create Date: 2026-09-09 08:36:37.231015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0e47b2d10b47'
down_revision: Union[str, None] = 'f45d3034c58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_memberships',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('membership_id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_memberships_org_user')
    )
    op.create_index(op.f('ix_organization_memberships_org_id'), 'organization_memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('platform_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_domain'), 'projects', ['domain'], unique=False)
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.add_column('alerts', sa.Column('project_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_alerts_project_id'), 'alerts', ['project_id'], unique=False)
    op.add_column('attribution_reviews', sa.Column('project_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_attribution_reviews_project_id'), 'attribution_reviews', ['project_id'], unique=False)
    op.add_column('ingested_experiments', sa.Column('project_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_ingested_experiments_project_id'), 'ingested_experiments', ['project_id'], unique=False)
    op.add_column('release_evaluations', sa.Column('project_id', sa.Text(), nullable=True))
    op.add_column('release_evaluations', sa.Column('economics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_release_evaluations_project_id'), 'release_evaluations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_evaluations_project_id'), table_name='release_evaluations')
    op.drop_column('release_evaluations', 'economics')
    op.drop_column('release_evaluations', 'project_id')
    op.drop_index(op.f('ix_ingested_experiments_project_id'), table_name='ingested_experiments')
    op.drop_column('ingested_experiments', 'project_id')
    op.drop_index(op.f('ix_attribution_reviews_project_id'), table_name='attribution_reviews')
    op.drop_column('attribution_reviews', 'project_id')
    op.drop_index(op.f('ix_alerts_project_id'), table_name='alerts')
    op.drop_column('alerts', 'project_id')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_domain'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_org_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    # ### end Alembic commands ###
