"""add project config, notification channels and delivery log

Revision ID: 15224ed5f9aa
Revises: 91419e63d02f
Create Date: 2026-09-09 23:33:35.128279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '15224ed5f9aa'
down_revision: Union[str, None] = '91419e63d02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index(op.f('ix_notification_channels_project_id'), 'notification_channels', ['project_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('payload_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id'),
    sa.UniqueConstraint('project_id', 'channel_id', 'event_type', 'dedup_key', name='uq_notification_delivery_dedup')
    )
    op.create_index(op.f('ix_notification_deliveries_channel_id'), 'notification_deliveries', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_created_at'), 'notification_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_event_type'), 'notification_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_project_id'), 'notification_deliveries', ['project_id'], unique=False)
    op.create_table('project_configs',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('primary_metric', sa.Text(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guardrails_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segment_dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('economics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monitoring_cadence_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled_notification_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_configs')
    op.drop_index(op.f('ix_notification_deliveries_project_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_event_type'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_created_at'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_channel_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_notification_channels_project_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
