"""scope ingestion identity uniqueness by project

Revision ID: 2236db0f2c7f
Revises: d36eacf8fd08
Create Date: 2026-09-09 20:37:02.572179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2236db0f2c7f'
down_revision: Union[str, None] = 'd36eacf8fd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ingested_experiments_domain_external_id'), 'ingested_experiments', type_='unique')
    op.create_unique_constraint('uq_ingested_experiments_project_domain_external_id', 'ingested_experiments', ['project_id', 'domain', 'external_experiment_id'])
    op.add_column('ingested_sessions', sa.Column('project_id', sa.Text(), nullable=True))
    # Backfill (Stage 8 task 1/4): ingested_sessions.project_id is
    # denormalized from its owning experiment purely so this table's own
    # uniqueness constraint can be project-scoped without a join. Existing
    # rows never had this column, so copy it from ingested_experiments —
    # this is a same-value backfill (not a new ownership assignment: a
    # session's project was always its experiment's project, this column
    # just makes that explicit here too), so it's safe to run
    # unconditionally and does not change what any query already returned.
    op.execute(
        "UPDATE ingested_sessions s SET project_id = e.project_id "
        "FROM ingested_experiments e WHERE e.experiment_id = s.experiment_id"
    )
    op.drop_constraint(op.f('uq_ingested_sessions_domain_external_id'), 'ingested_sessions', type_='unique')
    op.create_index(op.f('ix_ingested_sessions_project_id'), 'ingested_sessions', ['project_id'], unique=False)
    op.create_unique_constraint('uq_ingested_sessions_project_domain_external_id', 'ingested_sessions', ['project_id', 'domain', 'external_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ingested_sessions_project_domain_external_id', 'ingested_sessions', type_='unique')
    op.drop_index(op.f('ix_ingested_sessions_project_id'), table_name='ingested_sessions')
    op.create_unique_constraint(op.f('uq_ingested_sessions_domain_external_id'), 'ingested_sessions', ['domain', 'external_session_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('ingested_sessions', 'project_id')
    op.drop_constraint('uq_ingested_experiments_project_domain_external_id', 'ingested_experiments', type_='unique')
    op.create_unique_constraint(op.f('uq_ingested_experiments_domain_external_id'), 'ingested_experiments', ['domain', 'external_experiment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
