"""baseline schema

Revision ID: 4aa96d16451c
Revises: 
Create Date: 2026-09-06 13:28:50.042218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4aa96d16451c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('control_version', sa.String(length=16), nullable=False),
    sa.Column('treatment_version', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', name='experiment_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('laptop', 'monitor', 'accessory', name='product_category_enum'), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('price_rub', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('cpu_tier', sa.Enum('entry', 'mid', 'high', name='cpu_tier_enum'), nullable=True),
    sa.Column('gpu_tier', sa.Enum('integrated', 'entry_discrete', 'high_discrete', name='gpu_tier_enum'), nullable=True),
    sa.Column('screen_in', sa.Float(), nullable=True),
    sa.Column('use_case_tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signup_date', sa.Date(), nullable=False),
    sa.Column('platform_pref', sa.Enum('web', 'ios', 'android', name='platform_enum'), nullable=False),
    sa.Column('locale', sa.Enum('ru-RU', 'en-US', name='locale_enum'), nullable=False),
    sa.Column('persona', sa.Enum('budget', 'mainstream', 'power_user', 'gift_buyer', name='persona_enum'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('agent_version', sa.Enum('v1', 'v2', name='agent_version_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.Enum('web', 'ios', 'android', name='platform_enum'), nullable=False),
    sa.Column('device_tier', sa.Enum('low', 'mid', 'high', name='device_tier_enum'), nullable=False),
    sa.Column('locale', sa.Enum('ru-RU', 'en-US', name='locale_enum'), nullable=False),
    sa.Column('initial_query_text', sa.Text(), nullable=False),
    sa.Column('constraints_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_category', sa.Enum('laptop', 'monitor', 'accessory', name='product_category_enum'), nullable=False),
    sa.Column('num_constraints', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('purchase', 'add_to_cart_only', 'abandoned', 'no_action', name='session_outcome_enum'), nullable=False),
    sa.Column('num_turns', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('total_tokens_in', sa.Integer(), nullable=False),
    sa.Column('total_tokens_out', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_agent_version'), 'sessions', ['agent_version'], unique=False)
    op.create_index(op.f('ix_sessions_experiment_id'), 'sessions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_sessions_num_constraints'), 'sessions', ['num_constraints'], unique=False)
    op.create_index(op.f('ix_sessions_requested_category'), 'sessions', ['requested_category'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('understand_query', 'search', 'filter', 'clarify', 'recommend', 'answer', 'abandon_flow', name='action_type_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.Enum('v1', 'v2', name='agent_version_enum'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_agent_actions_session_id'), 'agent_actions', ['session_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('eval_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('eval_type', sa.Enum('offline_task_success', 'constraint_satisfaction', 'answer_faithfulness', name='eval_type_enum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evaluator', sa.Enum('rule_based', 'llm', name='evaluator_enum'), nullable=False),
    sa.Column('rationale_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('eval_id')
    )
    op.create_index(op.f('ix_evaluations_session_id'), 'evaluations', ['session_id'], unique=False)
    op.create_table('failure_labels',
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('failure_mode', sa.Enum('unnecessary_clarification', 'wrong_constraint_interpretation', 'poor_ranking', 'wrong_tool_selection', 'unsupported_product_claim', 'retrieval_failure', 'other', 'none', name='failure_mode_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('llm_classifier', name='failure_label_source_enum'), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_failure_labels_session_id'), 'failure_labels', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Enum('user', 'agent', name='message_sender_enum'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('product_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('impression', 'click', 'add_to_cart', 'purchase', 'remove_from_cart', name='product_event_type_enum'), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('price_at_event', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_product_events_product_id'), 'product_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_events_session_id'), 'product_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_product_events_user_id'), 'product_events', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('rec_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('satisfies_constraints', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_recommendations_product_id'), 'recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_recommendations_session_id'), 'recommendations', ['session_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.Enum('search_products', 'filter_products', 'get_product_details', 'compare_products', name='tool_name_enum'), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.Enum('none', 'timeout', 'empty_result', 'invalid_args', name='tool_error_type_enum'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.action_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_tool_calls_action_id'), 'tool_calls', ['action_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_session_id'), 'tool_calls', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_session_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_action_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_recommendations_session_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_product_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_product_events_user_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_session_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_product_id'), table_name='product_events')
    op.drop_table('product_events')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_failure_labels_session_id'), table_name='failure_labels')
    op.drop_table('failure_labels')
    op.drop_index(op.f('ix_evaluations_session_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_agent_actions_session_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_requested_category'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_num_constraints'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_experiment_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_agent_version'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('experiments')
    # ### end Alembic commands ###
