"""add project_id ownership column to commerce experiments

Revision ID: 8d13513cde22
Revises: 2236db0f2c7f
Create Date: 2026-09-09 20:39:56.680140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d13513cde22'
down_revision: Union[str, None] = '2236db0f2c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('project_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_experiments_project_id'), 'experiments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiments_project_id'), table_name='experiments')
    op.drop_column('experiments', 'project_id')
    # ### end Alembic commands ###
