"""add monitoring, connector run log, and release evaluation quality gating

Revision ID: 91419e63d02f
Revises: 8d13513cde22
Create Date: 2026-09-09 22:53:02.822878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91419e63d02f'
down_revision: Union[str, None] = '8d13513cde22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('connector', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('rows_fetched', sa.Integer(), nullable=True),
    sa.Column('matched_rows', sa.Integer(), nullable=True),
    sa.Column('unmatched_rows', sa.Integer(), nullable=True),
    sa.Column('validation_error_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_connector_runs_occurred_at'), 'connector_runs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_connector_runs_project_id'), 'connector_runs', ['project_id'], unique=False)
    op.create_table('monitoring_configs',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.Text(), nullable=False),
    sa.Column('primary_metric', sa.Text(), nullable=False),
    sa.Column('cadence_seconds', sa.Integer(), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_monitoring_configs_experiment_id'), 'monitoring_configs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_monitoring_configs_project_id'), 'monitoring_configs', ['project_id'], unique=False)
    op.create_table('monitoring_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.Text(), nullable=False),
    sa.Column('primary_metric', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('data_window_start', sa.DateTime(), nullable=True),
    sa.Column('data_window_end', sa.DateTime(), nullable=True),
    sa.Column('release_evaluation_id', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_monitoring_runs_config_id'), 'monitoring_runs', ['config_id'], unique=False)
    op.create_index(op.f('ix_monitoring_runs_experiment_id'), 'monitoring_runs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_monitoring_runs_project_id'), 'monitoring_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_monitoring_runs_started_at'), 'monitoring_runs', ['started_at'], unique=False)
    # raw_status has no meaningful default for existing rows -- every row
    # ever persisted was written before Stage 11's data-quality gating
    # existed, so its raw (un-gated) verdict is simply whatever `status`
    # already says. Added nullable first, backfilled, then tightened.
    op.add_column('release_evaluations', sa.Column('raw_status', sa.Text(), nullable=True))
    op.execute("UPDATE release_evaluations SET raw_status = status")
    op.alter_column('release_evaluations', 'raw_status', nullable=False)
    op.add_column('release_evaluations', sa.Column('data_quality_status', sa.Text(), server_default='healthy', nullable=False))
    op.add_column('release_evaluations', sa.Column('data_quality_gated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release_evaluations', 'data_quality_gated')
    op.drop_column('release_evaluations', 'data_quality_status')
    op.drop_column('release_evaluations', 'raw_status')
    op.drop_index(op.f('ix_monitoring_runs_started_at'), table_name='monitoring_runs')
    op.drop_index(op.f('ix_monitoring_runs_project_id'), table_name='monitoring_runs')
    op.drop_index(op.f('ix_monitoring_runs_experiment_id'), table_name='monitoring_runs')
    op.drop_index(op.f('ix_monitoring_runs_config_id'), table_name='monitoring_runs')
    op.drop_table('monitoring_runs')
    op.drop_index(op.f('ix_monitoring_configs_project_id'), table_name='monitoring_configs')
    op.drop_index(op.f('ix_monitoring_configs_experiment_id'), table_name='monitoring_configs')
    op.drop_table('monitoring_configs')
    op.drop_index(op.f('ix_connector_runs_project_id'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_occurred_at'), table_name='connector_runs')
    op.drop_table('connector_runs')
    # ### end Alembic commands ###
