"""add generic ingestion storage

Revision ID: a4ce37e9f060
Revises: def2e496a2d6
Create Date: 2026-09-08 20:03:52.155964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a4ce37e9f060'
down_revision: Union[str, None] = 'def2e496a2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_experiments',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('external_experiment_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('control_version', sa.Text(), nullable=False),
    sa.Column('treatment_version', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id'),
    sa.UniqueConstraint('domain', 'external_experiment_id', name='uq_ingested_experiments_domain_external_id')
    )
    op.create_table('ingested_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('external_session_id', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('agent_version', sa.Text(), nullable=False),
    sa.Column('external_user_id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_label', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['ingested_experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('domain', 'external_session_id', name='uq_ingested_sessions_domain_external_id')
    )
    op.create_index(op.f('ix_ingested_sessions_experiment_id'), 'ingested_sessions', ['experiment_id'], unique=False)
    op.create_table('ingested_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('external_action_id', sa.Text(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ingested_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('action_id'),
    sa.UniqueConstraint('session_id', 'external_action_id', name='uq_ingested_actions_session_external_id')
    )
    op.create_index(op.f('ix_ingested_actions_session_id'), 'ingested_actions', ['session_id'], unique=False)
    op.create_table('ingested_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('external_message_id', sa.Text(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ingested_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('session_id', 'external_message_id', name='uq_ingested_messages_session_external_id')
    )
    op.create_index(op.f('ix_ingested_messages_session_id'), 'ingested_messages', ['session_id'], unique=False)
    op.create_table('ingested_metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ingested_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('session_id', 'name', name='uq_ingested_metrics_session_name')
    )
    op.create_index(op.f('ix_ingested_metrics_session_id'), 'ingested_metrics', ['session_id'], unique=False)
    op.create_table('ingested_tool_calls',
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('external_tool_call_id', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['ingested_actions.action_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ingested_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('tool_call_id'),
    sa.UniqueConstraint('action_id', 'external_tool_call_id', name='uq_ingested_tool_calls_action_external_id')
    )
    op.create_index(op.f('ix_ingested_tool_calls_action_id'), 'ingested_tool_calls', ['action_id'], unique=False)
    op.create_index(op.f('ix_ingested_tool_calls_session_id'), 'ingested_tool_calls', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_tool_calls_session_id'), table_name='ingested_tool_calls')
    op.drop_index(op.f('ix_ingested_tool_calls_action_id'), table_name='ingested_tool_calls')
    op.drop_table('ingested_tool_calls')
    op.drop_index(op.f('ix_ingested_metrics_session_id'), table_name='ingested_metrics')
    op.drop_table('ingested_metrics')
    op.drop_index(op.f('ix_ingested_messages_session_id'), table_name='ingested_messages')
    op.drop_table('ingested_messages')
    op.drop_index(op.f('ix_ingested_actions_session_id'), table_name='ingested_actions')
    op.drop_table('ingested_actions')
    op.drop_index(op.f('ix_ingested_sessions_experiment_id'), table_name='ingested_sessions')
    op.drop_table('ingested_sessions')
    op.drop_table('ingested_experiments')
    # ### end Alembic commands ###
