"""add analysis window provenance to release evaluations and monitoring runs

Revision ID: c626a67754d3
Revises: 15224ed5f9aa
Create Date: 2026-09-10 12:40:15.297534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c626a67754d3'
down_revision: Union[str, None] = '15224ed5f9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_runs', sa.Column('window_hours', sa.Integer(), nullable=True))
    op.add_column('release_evaluations', sa.Column('data_window_start', sa.DateTime(), nullable=True))
    op.add_column('release_evaluations', sa.Column('data_window_end', sa.DateTime(), nullable=True))
    op.add_column('release_evaluations', sa.Column('window_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release_evaluations', 'window_hours')
    op.drop_column('release_evaluations', 'data_window_end')
    op.drop_column('release_evaluations', 'data_window_start')
    op.drop_column('monitoring_runs', 'window_hours')
    # ### end Alembic commands ###
