"""scope attribution review uniqueness by project

Revision ID: d36eacf8fd08
Revises: 0e47b2d10b47
Create Date: 2026-09-09 08:41:51.323997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd36eacf8fd08'
down_revision: Union[str, None] = '0e47b2d10b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_attribution_reviews_domain_session_mode'), 'attribution_reviews', type_='unique')
    op.create_unique_constraint('uq_attribution_reviews_domain_project_session_mode', 'attribution_reviews', ['domain', 'project_id', 'session_id', 'failure_mode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attribution_reviews_domain_project_session_mode', 'attribution_reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_attribution_reviews_domain_session_mode'), 'attribution_reviews', ['domain', 'session_id', 'failure_mode'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
