"""add session_failure_attributions multi-label table

Revision ID: def2e496a2d6
Revises: 4aa96d16451c
Create Date: 2026-09-08 14:09:53.562259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'def2e496a2d6'
down_revision: Union[str, None] = '4aa96d16451c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_failure_attributions',
    sa.Column('attribution_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('failure_mode', sa.Enum('retrieval_failure', 'poor_ranking', 'wrong_tool_selection', 'unnecessary_clarification', 'wrong_constraint_interpretation', 'unsupported_product_claim', name='failure_mechanism_enum'), nullable=False),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('detector_source', sa.Enum('deterministic', 'real_llm', 'mock_llm', name='detector_source_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('detector_version', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('attribution_id'),
    sa.UniqueConstraint('session_id', 'failure_mode', name='uq_session_failure_attributions_session_mode')
    )
    op.create_index(op.f('ix_session_failure_attributions_session_id'), 'session_failure_attributions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_failure_attributions_session_id'), table_name='session_failure_attributions')
    op.drop_table('session_failure_attributions')
    # ### end Alembic commands ###
    # Postgres native enums are not dropped automatically with the table.
    sa.Enum(name='failure_mechanism_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='detector_source_enum').drop(op.get_bind(), checkfirst=True)
