"""add alerts and attribution reviews tables

Revision ID: f45d3034c58d
Revises: 69525f9a3a9e
Create Date: 2026-09-08 22:22:47.991825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f45d3034c58d'
down_revision: Union[str, None] = '69525f9a3a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.Text(), nullable=False),
    sa.Column('evaluation_id', sa.Text(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('related_guardrail', sa.Text(), nullable=True),
    sa.Column('related_finding', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_domain'), 'alerts', ['domain'], unique=False)
    op.create_index(op.f('ix_alerts_experiment_id'), 'alerts', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('attribution_reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('failure_mode', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('corrected_mechanism', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('domain', 'session_id', 'failure_mode', name='uq_attribution_reviews_domain_session_mode')
    )
    op.create_index(op.f('ix_attribution_reviews_domain'), 'attribution_reviews', ['domain'], unique=False)
    op.create_index(op.f('ix_attribution_reviews_session_id'), 'attribution_reviews', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribution_reviews_session_id'), table_name='attribution_reviews')
    op.drop_index(op.f('ix_attribution_reviews_domain'), table_name='attribution_reviews')
    op.drop_table('attribution_reviews')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_experiment_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_domain'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
