"""Structured metric & variable provenance registry (METRICS.md, Stage 1
review requirement #5). A simple list of dataclasses, not a database table —
"stays simple" per the requirement, importable and printable directly.

Every metric declares:
  - source_tables: where its inputs come from
  - unit_of_measurement: what the raw value means
  - unit_of_inference: the row granularity a *significance test* would run
    on ("user" for anything inferential, matching STATISTICS.md SS2;
    "session" for purely descriptive counts like sessions_per_user which
    are already ratios at the population level)
  - numerator / denominator: exact definitions
  - eligibility_rule: which sessions/users are included
  - is_descriptive / is_inferential: whether it's shown as a raw number vs.
    fed into the cluster-level test-and-CI machinery in experiment_results.py
  - semantic_class: pre_treatment | treatment | post_treatment_mechanism |
    outcome | economic_outcome (Stage 1 review requirement #3) — this is
    the field the Stage 3 Investigation engine's segment-dimension registry
    must consult: only semantic_class == "pre_treatment" variables are
    eligible to *define* a segment.
  - cluster_stat_shape: which STATISTICS.md SS3 test row applies
    ("symmetric" -> Welch's t; "skewed" -> Mann-Whitney U); None for
    non-inferential or dimension entries.
  - implemented: whether Stage 2 actually computes this (some METRICS.md
    entries need failure_labels or an LLM judge and are deferred to Stage 3).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MetricDefinition:
    name: str
    semantic_class: str
    source_tables: tuple[str, ...]
    unit_of_measurement: str
    unit_of_inference: str
    numerator: str
    denominator: str
    eligibility_rule: str
    is_descriptive: bool
    is_inferential: bool
    cluster_stat_shape: str | None
    implemented: bool
    notes: str = ""
    # True for metrics whose underlying numerator counts discrete binary
    # events (conversion, clarification, ...) — these are additionally subject
    # to the minimum-event-count sparse-data rule (STATISTICS.md SS5), not
    # just the minimum-user-count rule. False for continuous measurements
    # (latency, turns, cost) and for fractional scores that aren't counts of
    # a binary event (constraint_satisfaction_rate).
    is_rate_metric: bool = False
    # Stage 4 (configurable metrics): optional display/config metadata.
    # Defaults keep any metric literal that omits these valid unchanged
    # (nothing in the analytics/decision engine reads them); a domain's
    # config-file-loaded metrics (backend.core.config.load_metric_config)
    # populate these explicitly. Commerce's own literals below set
    # metric_type/direction explicitly wherever the default ("rate" /
    # "higher_is_better") would be objectively wrong for a presentation
    # surface like the Stage 15 onboarding UI (e.g. abandonment_rate is
    # lower_is_better, cost/latency metrics aren't a "rate") — left
    # unset only where the correct value is itself ambiguous (e.g.
    # turns_per_session, clarification_rate).
    label: str = ""                        # human-readable display name; "" means "use name"
    metric_type: str = "rate"              # "rate" | "continuous" | "ratio" — presentation hint only
    direction: str = "higher_is_better"    # "higher_is_better" | "lower_is_better"


SEMANTIC_CLASSES = {"pre_treatment", "treatment", "post_treatment_mechanism", "outcome", "economic_outcome"}


METRIC_REGISTRY: list[MetricDefinition] = [
    MetricDefinition(
        name="conversion_rate",
        semantic_class="outcome",
        source_tables=("sessions",),
        unit_of_measurement="proportion of sessions",
        unit_of_inference="user",
        numerator="count(sessions where outcome='purchase')",
        denominator="count(sessions)",
        eligibility_rule="all sessions in the experiment window",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        notes="North star (METRICS.md SS1). Descriptive value is session-level; the significance verdict uses the per-user rate (STATISTICS.md SS2).",
        is_rate_metric=True,
        ),
    MetricDefinition(
        name="add_to_cart_rate",
        semantic_class="outcome",
        source_tables=("sessions",),
        unit_of_measurement="proportion of sessions",
        unit_of_inference="user",
        numerator="count(sessions where outcome in ('purchase','add_to_cart_only'))",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        is_rate_metric=True,
        ),
    MetricDefinition(
        name="abandonment_rate",
        semantic_class="outcome",
        source_tables=("sessions",),
        unit_of_measurement="proportion of sessions",
        unit_of_inference="user",
        numerator="count(sessions where outcome='abandoned')",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        is_rate_metric=True,
        direction="lower_is_better",
        ),
    MetricDefinition(
        name="impression_to_click_rate",
        semantic_class="outcome",
        source_tables=("product_events",),
        unit_of_measurement="proportion of sessions with >=1 impression",
        unit_of_inference="user",
        numerator="count(sessions with >=1 click event)",
        denominator="count(sessions with >=1 impression event)",
        eligibility_rule="sessions that reached a recommendation (>=1 impression)",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        notes="Funnel step 1 (METRICS.md SS2).",
        is_rate_metric=True,
        ),
    MetricDefinition(
        name="click_to_cart_rate",
        semantic_class="outcome",
        source_tables=("product_events",),
        unit_of_measurement="proportion of sessions with >=1 click",
        unit_of_inference="user",
        numerator="count(sessions with >=1 add_to_cart event)",
        denominator="count(sessions with >=1 click event)",
        eligibility_rule="sessions with >=1 click",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        notes="Funnel step 2.",
        is_rate_metric=True,
        ),
    MetricDefinition(
        name="cart_to_purchase_rate",
        semantic_class="outcome",
        source_tables=("product_events",),
        unit_of_measurement="proportion of sessions with >=1 add_to_cart",
        unit_of_inference="user",
        numerator="count(sessions with >=1 purchase event)",
        denominator="count(sessions with >=1 add_to_cart event)",
        eligibility_rule="sessions with >=1 add_to_cart",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        notes="Funnel step 3.",
        is_rate_metric=True,
        ),
    MetricDefinition(
        name="time_to_first_recommendation_ms",
        semantic_class="post_treatment_mechanism",
        source_tables=("recommendations", "sessions"),
        unit_of_measurement="milliseconds",
        unit_of_inference="user",
        numerator="min(recommendations.shown_at) - sessions.started_at, per session",
        denominator="n/a (per-session duration)",
        eligibility_rule="sessions with >=1 recommendation",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        metric_type="continuous",
        direction="lower_is_better",
    ),
    MetricDefinition(
        name="time_to_goal_seconds",
        semantic_class="outcome",
        source_tables=("sessions", "product_events"),
        unit_of_measurement="seconds",
        unit_of_inference="user",
        numerator="purchase event time (or session ended_at for abandoned) - sessions.started_at",
        denominator="n/a (per-session duration)",
        eligibility_rule="sessions with outcome in ('purchase','abandoned')",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="skewed",
        implemented=True,
        metric_type="continuous_skewed",
        direction="lower_is_better",
    ),
    MetricDefinition(
        name="turns_per_session",
        semantic_class="post_treatment_mechanism",
        source_tables=("sessions",),
        unit_of_measurement="count",
        unit_of_inference="user",
        numerator="sum(sessions.num_turns)",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        metric_type="continuous",
    ),
    MetricDefinition(
        name="click_through_rate_on_recommendations",
        semantic_class="outcome",
        source_tables=("recommendations",),
        unit_of_measurement="proportion of shown recommendations",
        unit_of_inference="user",
        numerator="count(recommendations.clicked = true)",
        denominator="count(recommendations)",
        eligibility_rule="all shown recommendations",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        is_rate_metric=True,
        notes="Descriptive only in Stage 2: this is a per-recommendation (not per-session) rate, and is materially redundant with impression_to_click_rate at the funnel-step level — running a second cluster test on the same underlying click behavior would not add information.",
        ),
    MetricDefinition(
        name="sessions_per_user",
        semantic_class="outcome",
        source_tables=("sessions",),
        unit_of_measurement="count",
        unit_of_inference="user",
        numerator="count(sessions)",
        denominator="count(distinct user_id)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        metric_type="continuous",
        notes="Already a user-level quantity by construction; not tested for significance in Stage 2 (not part of the rollout decision).",
    ),
    MetricDefinition(
        name="clarification_rate",
        semantic_class="post_treatment_mechanism",
        source_tables=("agent_actions",),
        unit_of_measurement="proportion of sessions",
        unit_of_inference="user",
        numerator="count(sessions with >=1 agent_actions.action_type='clarify')",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        is_rate_metric=True,
        ),
    MetricDefinition(
        name="unnecessary_clarification_rate",
        semantic_class="post_treatment_mechanism",
        source_tables=("sessions", "agent_actions"),
        unit_of_measurement="proportion of sessions with num_constraints>=3",
        unit_of_inference="user",
        numerator="count(sessions where num_constraints>=3 AND has clarify action)",
        denominator="count(sessions where num_constraints>=3)",
        eligibility_rule="sessions with num_constraints >= 3",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        notes="The diagnostic wired to planted effect overclarify_v2 (DATA_MODEL.md SS6).",
        is_rate_metric=True,
        direction="lower_is_better",
        ),
    MetricDefinition(
        name="tool_calls_per_session",
        semantic_class="post_treatment_mechanism",
        source_tables=("tool_calls",),
        unit_of_measurement="count",
        unit_of_inference="user",
        numerator="count(tool_calls)",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        metric_type="continuous",
    ),
    MetricDefinition(
        name="tool_success_rate",
        semantic_class="post_treatment_mechanism",
        source_tables=("tool_calls",),
        unit_of_measurement="proportion of tool calls",
        unit_of_inference="user",
        numerator="count(tool_calls.success = true)",
        denominator="count(tool_calls)",
        eligibility_rule="sessions with >=1 tool call",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        is_rate_metric=True,
        ),
    MetricDefinition(
        name="wrong_tool_selection_rate",
        semantic_class="post_treatment_mechanism",
        source_tables=("failure_labels",),
        unit_of_measurement="proportion of sessions",
        unit_of_inference="user",
        numerator="count(failure_labels.failure_mode='wrong_tool_selection')",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=False,
        is_inferential=False,
        cluster_stat_shape="symmetric",
        implemented=False,
        notes="Deferred to Stage 3: failure_labels is empty until the classifier (AI_EVALUATION.md) runs. Stage 2 uses tool_calls_per_session as an observable proxy for effect 5 (see effects_verification.py).",
    ),
    MetricDefinition(
        name="dead_end_rate",
        semantic_class="post_treatment_mechanism",
        source_tables=("agent_actions",),
        unit_of_measurement="proportion of sessions",
        unit_of_inference="user",
        numerator="count(sessions whose trajectory is search,search,search,abandon_flow)",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        is_rate_metric=True,
        direction="lower_is_better",
        ),
    MetricDefinition(
        name="action_sequence_length",
        semantic_class="post_treatment_mechanism",
        source_tables=("agent_actions",),
        unit_of_measurement="count",
        unit_of_inference="user",
        numerator="count(agent_actions)",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        metric_type="continuous",
    ),
    MetricDefinition(
        name="offline_task_success_rate",
        semantic_class="outcome",
        source_tables=("evaluations",),
        unit_of_measurement="proportion of evaluated sessions",
        unit_of_inference="user",
        numerator="count(evaluations.eval_type='offline_task_success' AND score>=0.7)",
        denominator="count(evaluations.eval_type='offline_task_success')",
        eligibility_rule="sessions that produced a recommendation (evaluations only exist for those)",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        notes="Computed deterministically (rule-based), not by an LLM (AI_EVALUATION.md SS6).",
        is_rate_metric=True,
        ),
    MetricDefinition(
        name="constraint_satisfaction_rate",
        semantic_class="outcome",
        source_tables=("evaluations",),
        unit_of_measurement="mean fraction of constraints satisfied",
        unit_of_inference="user",
        numerator="sum(evaluations.score where eval_type='constraint_satisfaction')",
        denominator="count(evaluations.eval_type='constraint_satisfaction')",
        eligibility_rule="sessions that produced a recommendation",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
    ),
    MetricDefinition(
        name="answer_faithfulness_score",
        semantic_class="outcome",
        source_tables=("evaluations",),
        unit_of_measurement="score 0-1",
        unit_of_inference="user",
        numerator="sum(evaluations.score where eval_type='answer_faithfulness')",
        denominator="count(evaluations.eval_type='answer_faithfulness')",
        eligibility_rule="sessions that produced a recommendation",
        is_descriptive=False,
        is_inferential=False,
        cluster_stat_shape="symmetric",
        implemented=False,
        notes="Deferred to Stage 3: this eval_type is LLM-judged (AI_EVALUATION.md SS6) and no rows exist yet.",
    ),
    MetricDefinition(
        name="p95_session_latency_ms",
        semantic_class="post_treatment_mechanism",
        source_tables=("sessions",),
        unit_of_measurement="milliseconds",
        unit_of_inference="user",
        numerator="95th percentile of sessions.total_latency_ms",
        denominator="n/a (percentile, not a ratio)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        metric_type="continuous",
        direction="lower_is_better",
        notes="Guardrail (METRICS.md SS5). METRICS.md defines this guardrail as a deterministic ratio-threshold check (flag if v2 p95 > v1 p95 x 1.15), not a hypothesis test — a percentile has no standard per-user cluster reduction the way a mean does, so Stage 2 reports it descriptively with the threshold check rather than a p-value/CI.",
    ),
    MetricDefinition(
        name="tool_error_rate",
        semantic_class="post_treatment_mechanism",
        source_tables=("tool_calls",),
        unit_of_measurement="proportion of tool calls",
        unit_of_inference="user",
        numerator="count(tool_calls.success = false)",
        denominator="count(tool_calls)",
        eligibility_rule="sessions with >=1 tool call",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="symmetric",
        implemented=True,
        notes="Guardrail.",
        is_rate_metric=True,
        direction="lower_is_better",
        ),
    MetricDefinition(
        name="unsupported_product_claim_rate",
        semantic_class="post_treatment_mechanism",
        source_tables=("failure_labels",),
        unit_of_measurement="proportion of sessions",
        unit_of_inference="user",
        numerator="count(failure_labels.failure_mode='unsupported_product_claim')",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=False,
        is_inferential=False,
        cluster_stat_shape="symmetric",
        implemented=False,
        notes="Deferred to Stage 3 (needs failure_labels).",
    ),
    MetricDefinition(
        name="cost_per_session_usd",
        semantic_class="economic_outcome",
        source_tables=("sessions",),
        unit_of_measurement="USD",
        unit_of_inference="user",
        numerator="sum(sessions.total_cost_usd)",
        denominator="count(sessions)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="skewed",
        implemented=True,
        metric_type="continuous_skewed",
        direction="lower_is_better",
        notes="Also the economic guardrail (METRICS.md SS5/SS6 — one definition, referenced from both).",
    ),
    MetricDefinition(
        name="revenue_per_session_usd",
        semantic_class="economic_outcome",
        source_tables=("product_events",),
        unit_of_measurement="USD (converted from RUB price_at_event)",
        unit_of_inference="user",
        numerator="sum(price_at_event where event_type='purchase')",
        denominator="count(sessions)",
        eligibility_rule="all sessions (0 revenue if no purchase)",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="skewed",
        implemented=True,
        metric_type="continuous_skewed",
        notes="Reported in USD-equivalent using a fixed illustrative RUB/USD rate for a single unified currency in the metric table; raw RUB values remain in product_events/products.",
    ),
    MetricDefinition(
        name="cost_per_successful_task_usd",
        semantic_class="economic_outcome",
        source_tables=("sessions",),
        unit_of_measurement="USD per purchase",
        unit_of_inference="n/a (ratio of two sums, not a per-user mean)",
        numerator="sum(sessions.total_cost_usd)",
        denominator="count(sessions where outcome='purchase')",
        eligibility_rule="all sessions in the arm",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        metric_type="continuous",
        direction="lower_is_better",
        notes="A ratio-of-sums (Kish-style) metric, not a per-session average — reported descriptively per arm with a bootstrap CI on the ratio itself rather than a cluster mean-difference test (see experiment_results.py).",
    ),
    MetricDefinition(
        name="gross_margin_proxy_usd",
        semantic_class="economic_outcome",
        source_tables=("product_events", "products"),
        unit_of_measurement="USD",
        unit_of_inference="user",
        numerator="sum(price_at_event * margin_pct) - sum(sessions.total_cost_usd)",
        denominator="n/a (absolute per-session margin)",
        eligibility_rule="all sessions",
        is_descriptive=True,
        is_inferential=True,
        cluster_stat_shape="skewed",
        implemented=True,
        metric_type="continuous_skewed",
    ),
    MetricDefinition(
        name="cost_to_serve_ratio",
        semantic_class="economic_outcome",
        source_tables=("sessions", "product_events"),
        unit_of_measurement="ratio (dimensionless)",
        unit_of_inference="n/a (ratio of two sums)",
        numerator="sum(sessions.total_cost_usd)",
        denominator="sum(revenue)",
        eligibility_rule="all sessions in the arm",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        metric_type="continuous",
        direction="lower_is_better",
    ),
    # --- pre-treatment dimensions (eligible for Stage 3 segment discovery) ---
    MetricDefinition(
        name="requested_category",
        semantic_class="pre_treatment",
        source_tables=("sessions",),
        unit_of_measurement="category label",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        notes="Fixed at session intake from the user's request, before any agent action (DATA_MODEL.md SS3.4).",
    ),
    MetricDefinition(
        name="constraint_count_bucket",
        semantic_class="pre_treatment",
        source_tables=("sessions",),
        unit_of_measurement="bucket label (0-1 / 2 / 3+)",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
    ),
    MetricDefinition(
        name="platform",
        semantic_class="pre_treatment",
        source_tables=("sessions",),
        unit_of_measurement="category label",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
    ),
    MetricDefinition(
        name="device_tier",
        semantic_class="pre_treatment",
        source_tables=("sessions",),
        unit_of_measurement="category label",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
    ),
    MetricDefinition(
        name="locale",
        semantic_class="pre_treatment",
        source_tables=("sessions", "users"),
        unit_of_measurement="category label",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
    ),
    MetricDefinition(
        name="persona",
        semantic_class="pre_treatment",
        source_tables=("users",),
        unit_of_measurement="category label",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        notes="Fixed per user (users.persona), not per session.",
    ),
    # --- treatment axis ---
    MetricDefinition(
        name="agent_version",
        semantic_class="treatment",
        source_tables=("sessions",),
        unit_of_measurement="v1 / v2 label",
        unit_of_inference="user",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        notes="The randomized comparison axis itself; assigned by hash(user_id, experiment_id) at the user level (DATA_MODEL.md SS3.4).",
    ),
    # --- post-treatment mechanism variables (never eligible to define a segment) ---
    MetricDefinition(
        name="trajectory_pattern",
        semantic_class="post_treatment_mechanism",
        source_tables=("agent_actions",),
        unit_of_measurement="ordered action-type sequence",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=False,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=False,
        notes="Constructed and analyzed in Stage 3 (INVESTIGATION.md SS5); not computed in Stage 2.",
    ),
    MetricDefinition(
        name="has_clarify_action",
        semantic_class="post_treatment_mechanism",
        source_tables=("agent_actions",),
        unit_of_measurement="boolean",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        notes="Agent-generated; feeds clarification_rate/unnecessary_clarification_rate as an explanatory mechanism, never a segmentation dimension (METRICS.md SS7).",
    ),
    MetricDefinition(
        name="tool_call_count",
        semantic_class="post_treatment_mechanism",
        source_tables=("tool_calls",),
        unit_of_measurement="count per session",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
    ),
    MetricDefinition(
        name="session_latency_ms",
        semantic_class="post_treatment_mechanism",
        source_tables=("sessions",),
        unit_of_measurement="milliseconds",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        notes="Also reported as the guardrail p95_session_latency_ms above; listed again here as a mechanism variable because Stage 3 uses it to explain abandonment (an association, not a segmentation dimension — METRICS.md SS7).",
    ),
    MetricDefinition(
        name="recommendation_properties",
        semantic_class="post_treatment_mechanism",
        source_tables=("recommendations",),
        unit_of_measurement="satisfies_constraints boolean, rank_position",
        unit_of_inference="n/a (dimension, not a metric)",
        numerator="n/a",
        denominator="n/a",
        eligibility_rule="n/a",
        is_descriptive=True,
        is_inferential=False,
        cluster_stat_shape=None,
        implemented=True,
        notes="What gets recommended is itself a post-treatment outcome of the agent's behavior — never used to define a segment (DATA_MODEL.md SS3.4's requested_category note).",
    ),
]


def get(name: str) -> MetricDefinition:
    from backend.core.metrics import get_metric

    return get_metric(name, METRIC_REGISTRY)


def pre_treatment_dimensions() -> list[MetricDefinition]:
    return [m for m in METRIC_REGISTRY if m.semantic_class == "pre_treatment"]


def implemented_inferential_metrics() -> list[MetricDefinition]:
    return [m for m in METRIC_REGISTRY if m.implemented and m.is_inferential]
